### ISSUE TITLE
Fails to build with boost 1.85 because of deprecated function

### ISSUE THREAD

**Issue by turol** [GrammaTech/ddisasm#78]
```
src/gtirb-builder/PeReader.cpp:399:42: error: ‘change_extension’ is not a member of ‘fs’
```
https://github.com/GrammaTech/ddisasm/blob/e1f3ca6ad4725bbdcb745e652fc2a71d9e7e8e76/src/gtirb-builder/PeReader.cpp#L399

It has been deprecated
https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html
